spring.application.name=assignment-service

server.port=9003


spring.datasource.url=jdbc:postgresql://postgres-assignments:5432/assignments_db
spring.datasource.username=postgres
spring.datasource.password=12345


eureka.client.service-url.defaultZone=http://eureka-server:9000/eureka/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


eureka.instance.prefer-ip-address=true

file.upload-dir=uploads
spring.cloud.openfeign.circuitbreaker.enabled=true

management.endpoints.web.exposure.include=health,info

resilience4j.circuitbreaker.instances.orderService.sliding-window-size=5
resilience4j.circuitbreaker.instances.orderService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.orderService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderService.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.driverService.sliding-window-size=5
resilience4j.circuitbreaker.instances.driverService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.driverService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.driverService.wait-duration-in-open-state=10s